#!/bin/bash

#----------------------------------------------------------------
#
#    DESCRIPTION: Telegram weather bot
#         AUTHOR: Kioller Alexey
#         E-MAIL: avkioller@gmail.com
#           DATE: 07.07.2017
#
#----------------------------------------------------------------

#==========VARIABLES========================================================

             KEY="$1"
         TIMEOUT="10"
             URL="https://api.telegram.org/bot$KEY"
         LOGFILE="/var/log/telebot.log"
     WEATHER_KEY="<INSERT YOUR KEY HERE>"        # https://www.worldweatheronline.com/
 WEATHER_REQUEST=$( tr -d " \n" <<< \
                 "https://api.worldweatheronline.com/premium/v1/weather.ashx?
                              key=$WEATHER_KEY&
                              q=Saint-Petersburg&
                              format=json&
                              date=today&
                              lang=ru" )

#==========FUNCTIONS========================================================

function send_text {
    curl -s --max-time "$TIMEOUT"                                       \
            --output /dev/null                                          \
            -d "chat_id=$CHAT_ID&disable_web_page_preview=1&text=$TEXT" \
            "$URL/sendMessage"
}

#===========================================================================

while sleep 1;
do
    RAW_MESSAGE=$( curl -s "$URL/getUpdates?offset=-1" )
     MESSAGE_ID=$( jq .result[0].message.message_id    <<< "$RAW_MESSAGE" )
        CHAT_ID=$( jq .result[0].message.chat.id       <<< "$RAW_MESSAGE" )
        MESSAGE=$( jq .result[0].message.text          <<< "$RAW_MESSAGE" | sed 's/^"\|"$//g' )
         SENDER=$( jq .result[0].message.from.username <<< "$RAW_MESSAGE" | tr -d '"' )

    if [[ "$MESSAGE_ID" -ne "$LAST_ID" ]] 
    then
        case "$MESSAGE" in

            /weather|[Пп]огода)

                RAW_WEATHER=$( curl -s "$WEATHER_REQUEST" )
                       TEMP=$( jq .data.current_condition[0].temp_C           <<< "$RAW_WEATHER" | sed 's/^"\|"$//g' | sed '/^[0-9]/s/^/%2B/')
                    COMMENT=$( jq .data.current_condition[0].lang_ru[0].value <<< "$RAW_WEATHER" | sed 's/^"\|"$//g' )
                UPDATE_TIME=$( jq .data.current_condition[0].observation_time <<< "$RAW_WEATHER" | sed 's/^"\|"$//g;s/ .*//' | xargs -i date -d "TZ=\"UTC\" {}" +"%H:%M" )

                TEXT="[$UPDATE_TIME]: $TEMP $COMMENT"
                send_text && sed 's/%2B/+/g' <<<                             \
                             "$( date +"[%H:%M]: \"" )$TEXT\" to @$SENDER"   \
                             >> "$LOGFILE"
                ;;

            /start|/info)

                TEXT="This is my own bot writed on Bash. @Cuttlerat"
                send_text
                ;;

        esac
        LAST_ID="$MESSAGE_ID"
    fi
done
