#!/bin/bash
touch database.db
chmod 600 database.db
if [[ ! -f tokens ]]; then
    touch tokens
    echo "BOT_TOKEN=YOUR_TELEGRAM_TOKEN_HERE" > tokens
    echo "WEATHER_TOKEN=YOUR_WEATHER_KEY_HERE" >> tokens
fi
chmod 600 tokens
rm $0
