#!/bin/bash

# This is my CI for https://github.com/Cuttlerat/bashbot

cd ~/Git/bashbot/

while :; do
    inotifywait -e modify ./bashbot
    sudo docker build -t bashbot .
    sudo docker kill $( sudo docker ps | grep bashbot | awk '{print $1}' )
done
