#!/bin/bash

# This is my CI for https://github.com/Cuttlerat/bashbot

cd /bashbot

while :; do
    inotifywait -e modify ./bashbot
    #docker build -t bashbot .
    #docker rm -f bashbot
    docker-compose stop -t 1 bashbot
    docker-compose build bashbot
    docker-compose create bashbot
    docker-compose start bashbot
done
