#!/usr/bin/env bash

# This is my CI for https://github.com/Cuttlerat/bashbot

#===  FUNCTION  ================================================================
#          NAME:  _log_echo
#   DESCRIPTION:  Echo into log with timestamp
#===============================================================================
function _log_echo {

    local message="$@"
    date +"[%d/%b/%Y:%H:%M:%S %z]: ${message[@]}" 1>&2

}    # ----------  end of function _log_echo  ----------

cd /bashbot

while _log_echo "Waiting for updates" &&\
      inotifywait -e modify ./bashbot &>/dev/null; do

    _log_echo "Building new bashbot"
    docker-compose build bashbot &>/dev/null       \
        || _log_echo "Error while building"

    _log_echo "Creating new container for bashbot"
    docker-compose create bashbot &>/dev/null      \
        || _log_echo "Error while creating"

    _log_echo "Restarting bashbot"
    docker-compose restart bashbot &>/dev/null     \
        || _log_echo "Error while restarting"

done
