#!/bin/bash

CONFIG="$( dirname $0 )/.start_info"

if [[ -s "${CONFIG}" ]]; then
    source "${CONFIG}"
else 
    cat <<EOF 

You need to create a file .start_info into directory with this script
and declare two variables "BOT_TOKEN" and "WEATHER_TOKEN" in this file
Example of .start_info file:

BOT_TOKEN="YOUR BOT TOKEN"
WEATHER_TOKEN="YOUR WEATHER TOKEN"

EOF
    exit 1
fi

[[ ${BOT_TOKEN?"BOT_TOKEN is not declared in .start_info file"} ]]
[[ ${WEATHER_TOKEN?"WEATHER_TOKEN is not declared in .start_info file"} ]]

while :; do
    sudo docker run -it                                     \
                --pids-limit 100                            \
                -v ~/Git/bashbot/data:/data                 \
                --name bashbot                              \
                bashbot ${BOT_TOKEN} ${WEATHER_TOKEN}       \
                2>/dev/null                                 \
    || [[ $? -eq 125 ]]                                     \
    && sudo docker rm -f bashbot &>/dev/null                \
    && ./$0
done
